version: '3.7'
services:
  elasticsearch:
    image: blacktop/elasticsearch:7.0
    ports:
      - 9201:9200
    networks:
      - log-analysis
  kibana:
    image: blacktop/kibana:7.0
    environment:
      - ELASTICSEARCH_HOSTS=['http://elasticsearch:9200']
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - log-analysis
networks:
  log-analysis:

